version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: achatina-asa-bot
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - achatina

networks:
  achatina:
    external: true